version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby

    working_directory: ~/repo

    steps:
      - checkout
      - run: "sh ./script/ci-build"
      - save_cache:
          key: gem-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - vendor/bundle

  release:
    docker:
      - image: circleci/ruby

    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          keys:
            - gem-cache-{{ .Branch }}-{{ .Revision }}
      - run: "sh ./script/ci-release"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: Archmix
      - release:
          context: Archmix
          requires:
            - build
          filters:
            branches:
              only: master
