version: 2.1
executors:
  docker-executor:
    environment:
      IMAGE_NAME: <IMAGE-NAME>
    docker:
      - image: circleci/buildpack-deps:stretch

commands:
  docker_build:
    parameters:
      org_name:
        type: string
        default: archmixoss
      image_name:
        type: string
      image_version:
        type: string
        default: latest
      dockerfile:
        type: string
    steps:
      - run:
          name: Build Docker image
          command: |
            docker build -t << parameters.org_name >>/<< parameters.image_name >>:<< parameters.image_version >> << parameters.dockerfile >>
      - run:
          name: Archive Docker image
          command: docker save -o << parameters.org_name >>_<< parameters.image_name >>.tar << parameters.org_name >>/<< parameters.image_name >>
      - persist_to_workspace:
          root: .
          paths:
            - ./<< parameters.org_name >>_<< parameters.image_name >>.tar
  
  docker_login:
    steps:
      - run:
          name: Sign in to docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER_NAME" --password-stdin

  docker_push:
    parameters:
      org_name:
        type: string
        default: archmixoss
      image_name:
        type: string
      image_version:
        type: string
        default: latest
      should_tag:
        type: boolean
        default: false
    steps:
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/<< parameters.org_name >>_<< parameters.image_name >>.tar
      - docker_login
      - when:
          condition: <<parameters.should_tag>>
          steps:
            - run: docker tag << parameters.org_name >>/<< parameters.image_name >>:latest << parameters.org_name >>/<< parameters.image_name >>:<< parameters.image_version >>
            - run: docker push << parameters.org_name >>/<< parameters.image_name >>:latest
      - run:
          name: Push Docker Image to Docker Hub
          command: docker push << parameters.org_name >>/<< parameters.image_name >>:<< parameters.image_version >>

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - docker_build:
          image_name: $IMAGE_NAME
          image_version: latest
          dockerfile: ./

  release:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - docker_push :
          image_name: $IMAGE_NAME
          image_version: latest

  release-tag:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - docker_push :
          image_name: $IMAGE_NAME
          image_version: ${CIRCLE_TAG/v/''}
          should_tag : true

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: Archmix
      - release:
          context: Archmix
          requires:
            - build
          filters:
            branches:
              only: master
  build-tags:
    jobs:
      - build:
          context: Archmix
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - release-tag:
          context: Archmix
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
